
---
spring:
    profiles: postgresql
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true

        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: update
            # dll-auto: none
            # ddl-auto: create-drop
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            properties:
                hibernate:
                    enable_lazy_load_no_trans: false
                    order_inserts: true
                    order_updates: true
                    jdbc:
                        fetch_size: 100
                        batch_size: 20
                        batch_versioned_data: true
                    hbm2ddl:
                        delimiter: ";"

        properties:
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
                    schema-generation:
                        scripts:
                            create-target: schema-generation/my-schema.sql
                            action: none

            hibernate:
                generate_statistics: false
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                hikari:
                    maximumPoolSize: 30
                cache:
                    #required - turn on L2 cache.
                    use_second_level_cache: true
                    #optional - turn on query cache.
                    use_query_cache: true
                    region:
                        #required - classpath to cache region factory.
                        factory_class:  org.hibernate.cache.jcache.JCacheRegionFactory

                javax:
                    cache:
                        provider: org.ehcache.jsr107.EhcacheCachingProvider
                        uri: classpath:ehcache.xml

    cache:
        jcache:
            config: classpath:ehcache.xml

    # Herokuâ€™s support for Java will now set the SPRING_DATASOURCE_URL environment variable for all Java apps using a SQL Database add-on.
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        #url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.1.4:5432/qcm?user=qcm&password=qcm}
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.1.4:5433/postgres?user=postgres&password=postgres}
        hikari:
            url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.1.4:5433/postgres?user=postgres&password=postgres}
            pool-name: qcm-hikari-pool
            autoCommit: false
            connection-test-query: SELECT 1
            idleTimeout: 20000
            minimum-idle: 1
            maximumPoolSize: 5

