
---
spring:
    profiles: brix
    jpa:
        # open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        show-sql: true
        hibernate:
          # #dll-auto: none
             ddl-auto: update
             # ddl-auto: create-drop
             dialect: org.hibernate.dialect.PostgreSQLDialect
             properties:
                 hibernate:
                     enable_lazy_load_no_trans: false
                     generate_statistics: true
                     order_inserts: true
                     order_updates: true
                     jdbc:
                         fetch_size: 100
                         batch_size: 20
                         batch_versioned_data: true

             cache:
                 use_second_level_cache: false
                 use_query_cache: false
                 region:
                     factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

        properties:
            javax:
                persistence:
                     sharedCache:
                          mode: ENABLE_SELECTIVE

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.100:5432/qcm
        username: mynotes
        password: mynotes